# There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

In [10]:
from operator import mul
from functools import reduce

I tried three methods from the Wikipedia article and then found a general method here: 
https://math.stackexchange.com/questions/2935767/do-all-primitive-triples-belong-to-the-plato-pythagoras-and-fermat-families

In [4]:
def is_pythag_triplet(a,b,c):
    return a**2 + b**2 == c**2

In [12]:
for i in range(100):
    t = (3*i,4*i,5*i)
    assert(is_pythag_triplet(*t))
    print("%s + %s + %s = %s" % (*t,sum(t)))

0 + 0 + 0 = 0
3 + 4 + 5 = 12
6 + 8 + 10 = 24
9 + 12 + 15 = 36
12 + 16 + 20 = 48
15 + 20 + 25 = 60
18 + 24 + 30 = 72
21 + 28 + 35 = 84
24 + 32 + 40 = 96
27 + 36 + 45 = 108
30 + 40 + 50 = 120
33 + 44 + 55 = 132
36 + 48 + 60 = 144
39 + 52 + 65 = 156
42 + 56 + 70 = 168
45 + 60 + 75 = 180
48 + 64 + 80 = 192
51 + 68 + 85 = 204
54 + 72 + 90 = 216
57 + 76 + 95 = 228
60 + 80 + 100 = 240
63 + 84 + 105 = 252
66 + 88 + 110 = 264
69 + 92 + 115 = 276
72 + 96 + 120 = 288
75 + 100 + 125 = 300
78 + 104 + 130 = 312
81 + 108 + 135 = 324
84 + 112 + 140 = 336
87 + 116 + 145 = 348
90 + 120 + 150 = 360
93 + 124 + 155 = 372
96 + 128 + 160 = 384
99 + 132 + 165 = 396
102 + 136 + 170 = 408
105 + 140 + 175 = 420
108 + 144 + 180 = 432
111 + 148 + 185 = 444
114 + 152 + 190 = 456
117 + 156 + 195 = 468
120 + 160 + 200 = 480
123 + 164 + 205 = 492
126 + 168 + 210 = 504
129 + 172 + 215 = 516
132 + 176 + 220 = 528
135 + 180 + 225 = 540
138 + 184 + 230 = 552
141 + 188 + 235 = 564
144 + 192 + 240 = 576
147 + 196 + 245 = 588
150 + 200 + 250 = 600
153 + 204 + 255 = 612
156 + 208 + 260 = 624
159 + 212 + 265 = 636
162 + 216 + 270 = 648
165 + 220 + 275 = 660
168 + 224 + 280 = 672
171 + 228 + 285 = 684
174 + 232 + 290 = 696
177 + 236 + 295 = 708
180 + 240 + 300 = 720
183 + 244 + 305 = 732
186 + 248 + 310 = 744
189 + 252 + 315 = 756
192 + 256 + 320 = 768
195 + 260 + 325 = 780
198 + 264 + 330 = 792
201 + 268 + 335 = 804
204 + 272 + 340 = 816
207 + 276 + 345 = 828
210 + 280 + 350 = 840
213 + 284 + 355 = 852
216 + 288 + 360 = 864
219 + 292 + 365 = 876
222 + 296 + 370 = 888
225 + 300 + 375 = 900
228 + 304 + 380 = 912
231 + 308 + 385 = 924
234 + 312 + 390 = 936
237 + 316 + 395 = 948
240 + 320 + 400 = 960
243 + 324 + 405 = 972
246 + 328 + 410 = 984
249 + 332 + 415 = 996
252 + 336 + 420 = 1008
255 + 340 + 425 = 1020
258 + 344 + 430 = 1032
261 + 348 + 435 = 1044
264 + 352 + 440 = 1056
267 + 356 + 445 = 1068
270 + 360 + 450 = 1080
273 + 364 + 455 = 1092
276 + 368 + 460 = 1104
279 + 372 + 465 = 1116
282 + 376 + 470 = 1128
285 + 380 + 475 = 1140
288 + 384 + 480 = 1152
291 + 388 + 485 = 1164
294 + 392 + 490 = 1176
297 + 396 + 495 = 1188

In [25]:
#construct pythag triples using Stifel method.

triples=[]

def construct(frac):
    return[frac[2], (frac[0]*frac[2])+frac[1],(frac[0]*frac[2])+frac[1]+1]
    
for i in range(1,50):
    triple = construct([i,i,1+(2*i)])
    assert is_pythag_triplet(*triple)
    print(triple, sum(triple))
    if(sum(triple) == 1000):
        break
    triples.append(triple)

[3, 4, 5] 12
[5, 12, 13] 30
[7, 24, 25] 56
[9, 40, 41] 90
[11, 60, 61] 132
[13, 84, 85] 182
[15, 112, 113] 240
[17, 144, 145] 306
[19, 180, 181] 380
[21, 220, 221] 462
[23, 264, 265] 552
[25, 312, 313] 650
[27, 364, 365] 756
[29, 420, 421] 870
[31, 480, 481] 992
[33, 544, 545] 1122
[35, 612, 613] 1260
[37, 684, 685] 1406
[39, 760, 761] 1560
[41, 840, 841] 1722
[43, 924, 925] 1892
[45, 1012, 1013] 2070
[47, 1104, 1105] 2256
[49, 1200, 1201] 2450
[51, 1300, 1301] 2652
[53, 1404, 1405] 2862
[55, 1512, 1513] 3080
[57, 1624, 1625] 3306
[59, 1740, 1741] 3540
[61, 1860, 1861] 3782
[63, 1984, 1985] 4032
[65, 2112, 2113] 4290
[67, 2244, 2245] 4556
[69, 2380, 2381] 4830
[71, 2520, 2521] 5112
[73, 2664, 2665] 5402
[75, 2812, 2813] 5700
[77, 2964, 2965] 6006
[79, 3120, 3121] 6320
[81, 3280, 3281] 6642
[83, 3444, 3445] 6972
[85, 3612, 3613] 7310
[87, 3784, 3785] 7656
[89, 3960, 3961] 8010
[91, 4140, 4141] 8372
[93, 4324, 4325] 8742
[95, 4512, 4513] 9120
[97, 4704, 4705] 9506
[99, 4900, 4901] 9900

In [28]:
#construct pythag triples using Ozanam method.

triples=[]

def construct(frac):
    return[frac[2], (frac[0]*frac[2])+frac[1],(frac[0]*frac[2])+frac[1]+2]
    
for i in range(1,50):
    triple = construct([i,(i*4)+3,(i*4)+4])
    assert is_pythag_triplet(*triple)
    print(triple, sum(triple))
    if(sum(triple) == 1000):
        break
    triples.append(triple)

[8, 15, 17] 40
[12, 35, 37] 84
[16, 63, 65] 144
[20, 99, 101] 220
[24, 143, 145] 312
[28, 195, 197] 420
[32, 255, 257] 544
[36, 323, 325] 684
[40, 399, 401] 840
[44, 483, 485] 1012
[48, 575, 577] 1200
[52, 675, 677] 1404
[56, 783, 785] 1624
[60, 899, 901] 1860
[64, 1023, 1025] 2112
[68, 1155, 1157] 2380
[72, 1295, 1297] 2664
[76, 1443, 1445] 2964
[80, 1599, 1601] 3280
[84, 1763, 1765] 3612
[88, 1935, 1937] 3960
[92, 2115, 2117] 4324
[96, 2303, 2305] 4704
[100, 2499, 2501] 5100
[104, 2703, 2705] 5512
[108, 2915, 2917] 5940
[112, 3135, 3137] 6384
[116, 3363, 3365] 6844
[120, 3599, 3601] 7320
[124, 3843, 3845] 7812
[128, 4095, 4097] 8320
[132, 4355, 4357] 8844
[136, 4623, 4625] 9384
[140, 4899, 4901] 9940
[144, 5183, 5185] 10512
[148, 5475, 5477] 11100
[152, 5775, 5777] 11704
[156, 6083, 6085] 12324
[160, 6399, 6401] 12960
[164, 6723, 6725] 13612
[168, 7055, 7057] 14280
[172, 7395, 7397] 14964
[176, 7743, 7745] 15664
[180, 8099, 8101] 16380
[184, 8463, 8465] 17112
[188, 8835, 8837] 17860
[192, 9215, 9217] 18624
[196, 9603, 9605] 19404
[200, 9999, 10001] 20200

In [48]:
#general method
def generate_general(m,n):
    assert m > n
    a = m**2 - n**2
    b = 2*m*n
    c = m**2+ n**2
    triple = [a,b,c]
    assert is_pythag_triplet(*triple)
    return triple

for j in range(1,40):
    for i in range(3,100):
        triple = generate_general(i+j,i)
        if sum(triple) == 1000:
            print("WOO!",triple)

        #print(triple, sum(triple))

WOO! [375, 200, 425]

In [49]:
375 * 200 * 425

31875000